name: Update Deployment Repository

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout deployment repository
      uses: actions/checkout@v2
      with:
        repository: yb2411/nginx-hello-world1
        token: ${{ secrets.DEPLOYMENT_REPO_TOKEN }}

    - name: Update image tag in Helm values
      run: |
        cd .
        sed -i "s|yb2411/pythonweb:.+|yb2411/pythonweb:${{ github.sha }}|g" values.yaml

    - name: Update image tag in deployment repository
      run: |
        sed -i 's@tag: [^ ]*@tag: ${{ github.sha }}@g' ./values.yaml
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./values.yaml
        git commit -m "Update image tag in deployment repository"
        git push